taxa_elitismo: 0.1
taxa_mutacao: 0.05
tamanho_populacao: 100
geracoes: 200
tipo_geracao: apenas_movimentos_validos
max_tamanho_individuo: 300
penalidade_movimento_invalido: true
saida_log: logs/experimento1.csv
